#!/usr/bin/perl
use strict;
use warnings;
use 5.10.0;
use autodie ':all';
use Pod::Usage;
use Text::MicroTemplate;

&main; exit;

sub main {
    my $project = shift @ARGV or pod2usage;

    die "$project is already exists." if -e $project;

    mkdir($project);
    chdir($project);

    write_files($project);

    system('touch NEWS README AUTHORS ChangeLog');

    system('aclocal; autoheader; automake -a -c; autoconf');
    system('./configure');
    system('make');
    system('make distclean');

    system('git init');
    system('git add .');
    system('git commit -m "initial import"');
}

sub write_files {
    my $project = shift;

    write_file('main.cc', <<'...');
#include <stdio.h>
int main() { puts("HELLO"); }
...

    write_file('configure.in', <<'...', $project);
? my ($project) = @_;
#                                               -*- Autoconf -*-
# Process this file with autoconf to produce a configure script.
AC_PREREQ([2.68])
AC_INIT([<?= $project ?>], [0.1], [tokuhirom+bugs@gmail.com])
AM_INIT_AUTOMAKE
AC_CONFIG_SRCDIR([main.cc])
AC_CONFIG_HEADERS([config.h])
AC_CONFIG_FILES([Makefile])

# Checks for programs.
AC_PROG_CXX

# Checks for libraries.

# Checks for header files.

# Checks for typedefs, structures, and compiler characteristics.

# Checks for library functions.

AC_OUTPUT
...

    write_file('Makefile.am', <<'...', $project);
? my $project = shift;
bin_PROGRAMS = <?= $project ?>
<?= $project ?>_SOURCES = main.cc
...

    write_file('COPYING', <<'...');
? use Time::Piece qw(localtime);
The MIT License (MIT)

Copyright    <?= localtime->year ?> Tokuhiro Matsuno, http://64p.org/ <tokuhirom@gmail.com>

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the    Software   ), to deal
in the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED    AS IS   , WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
...

    write_file('.gitignore', <<'...', $project);
? my $project = shift;
<%= $project %>
config.h
.deps/
Makefile
Makefile.in
aclocal.m4
autom4te.cache/
config.log
config.status
configure
depcomp
install-sh
missing
stamp-h1
...
}

sub write_file {
    my ($fname, $tmpl, @args) = @_;

    my $mt = Text::MicroTemplate->new(escape_func => sub { $_[0] }, template => $tmpl);
    my $content = (eval $mt->code)->(@args);
    open my $fh, '>', $fname;
    print $fh $content;
    close $fh;
}

__END__

=head1 NAME

cxxsetup - c++ setup script

=head1 SYNOPSIS

    $ cxxsetup myapp

